version: '3.8'

services:
  springboot-stream-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio_demo_streaming
      - MINIO_SECRET_KEY=minio_demo_streaming_secret_key
      - MINIO_BUCKET_NAME=video-bucket
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio_demo_streaming
      - MINIO_SECRET_KEY=minio_demo_streaming_secret_key
    command: server /data
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data:
